#roles:
#  - name: demo
#    version: main
#    scm: git
#    src: https://github.com/gigi206/ansible_galaxy_demo
#    #src: git@github.com/gigi206/ansible_galaxy_demo.git:/gigix/demo/roles/demo

collections:
  - name: gigix.demo
    src: https://github.com/gigi206/ansible_galaxy_demo/archive/refs/heads/main.zip
